def code_challenge3():
    Name = input("Please type your name: ")
    Age = input("Please type your age: ")
    Mobile = input("Please type your mobile: ")
    EmailId = input("Please type your email address: ")
    FatherName = input("Please type your Father's name: ")
    Gender = input("Please type your Gender: ")
    DOB = input("Please type your Date of Birth: ")
    MaritalStatus = input("Please type your Marital Status: ")
    Religion = input("Please type your Religion: ")
    LanguageKnown = input("Please type your Language Learn: ")
    Address = input("Please type your Address: ")
    
    print("Hello my name is " , Name , ".")
    print("I'm " , Age , "years old.")
    print("I live in " , Address , ".")
    print("My mobile number is " , Mobile , ".") 
    print("My email address is " , EmailId , ".")
    print("My father's name is " , FatherName , ".")
    print("My gender is " , Gender , ".")
    print("I was born on " , DOB , ".")
    print("My marital status is " , MaritalStatus, ".")
    print("My religion is " , Religion , ".")
    print("I know " , LanguageKnown , "language.")
